geii_stock:
    resource: "@GEIIStockBundle/Controller/"
    type:     annotation
    prefix:   /

geii_stock:
    resource: "@GEIIStockBundle/Controller/"
    type:     annotation
    prefix:   /consulter-reference


