<?php
 
namespace GEII\StockBundle\Entity\Repository;
 
use Doctrine\ORM\EntityRepository;
 
/**
 * JournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends EntityRepository
{
 
    public function getAllQte()
    {
        $query =  $this->_em->createQuery('
         	SELECT sum(j.quantite)
    		FROM GEIIStockBundle:Journal j');
    	return $query->getSingleScalarResult();
    }

    public function getPrixHT()
    {
        $query =  $this->_em->createQuery('
         	SELECT sum(j.prixht)
    		FROM GEIIStockBundle:Journal j');
    	return $query->getSingleScalarResult();
    }

    public function getPrixTTC()
    {
        $query =  $this->_em->createQuery('
         	SELECT sum(j.prixttc)
    		FROM GEIIStockBundle:Journal j');
    	return $query->getSingleScalarResult();
    }

}